### ISSUE TITLE
cannot install. problem with imp?

### ISSUE THREAD

**Issue by teoshannon** [quadrismegistus/prosodic#55]
using:
`py -m pip install git+https://github.com/quadrismegistus/prosodic.git`

receiving this error:

` error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tarci\AppData\Local\Temp\pip-req-build-66pyz14l\setup.py", line 20, in <module>
          import sys,os,imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

**Comment by quadrismegistus** [comment]
What versio nof python are you running?

**Comment by teoshannon** [comment]
The latest. I just installed it a couple weeks ago.On Dec 9, 2023, at 07:58, Dr. Ryan Heuser ***@***.***> wrote:﻿
What versio nof python are you running?

**Comment by teoshannon** [comment]
Also, as a followup, Scott Borgeson recommended I use this program, and, as an alternative, [](prosodic.stanford.edu) but that also is not working well. i consistently receive a 504 timeout, or it fails to parse a line and stops functioning (unless i delete the line, which isn't good, obviously), or fails to handle a line longer than, say, 15 syllables.

**Comment by quadrismegistus** [comment]
The code is so old and clunky that I resorted recently to rewriting it all. It's still in another branch but is doing better than original by now I think: https://github.com/quadrismegistus/prosodic/tree/develop

There's instructions there in the README if you want to check it out. Would appreciate any feedback, too

**Comment by teoshannon** [comment]
Thanks, here's the latest

`  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "C:\Users\tarci\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\tarci\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tarci\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tarci\AppData\Local\Temp\pip-build-env-7449r1r6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tarci\AppData\Local\Temp\pip-build-env-7449r1r6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\tarci\AppData\Local\Temp\pip-build-env-7449r1r6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "C:\Users\tarci\AppData\Local\Temp\pip-build-env-7449r1r6\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tarci\AppData\Local\Temp\pip-build-env-7449r1r6\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\tarci\AppData\Local\Temp\pip-build-env-7449r1r6\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'editdistance/bycython.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

**Comment by quadrismegistus** [comment]
Yep, I'm getting same error with Python 3.12. It looks like one of the dependencies (prosodic -> syllabiphon -> editdistance) isn't working with 3.12. Python 3.11 works for me, though, if you give that a try. You probably already have a system for doing this but I use pyenv to keep track of python versions so it'd be:

```
# install pyenv if nec
curl -sS https://webi.sh/pyenv | sh

# install 3.11
pyenv install 3.11

# activate 3.11
pyenv shell 3.11

# create venv
python -m venv venv

# activate venv
. venv/bin/activate

# install
pip install git+https://github.com/quadrismegistus/prosodic@develop
```

Does that work?

**Comment by teoshannon** [comment]
Hi Ryan,

Even running in 3.11.0, I encounter the same error

**Comment by quadrismegistus** [comment]
Try again. It even works for me on 3.12 now. Fixed it [from this comment](https://github.com/roy-ht/editdistance/issues/94#issuecomment-1426279375).

**Comment by quadrismegistus** [comment]
Does this issue still persist? Prosodic has been updated. `pip install prosodic` works for me on 3.12

**Comment by quadrismegistus** [comment]
Closing this for now but feel free to comment/re-open
